---@class Entity
---@field _id? string
---@field health? Health
---@field name? string
---@field group? 'player'|'enemy'|'ally'
---@field inventory? ItemData[]
---@field max_inventory_items? number
---@field equipped_items? ItemData[]
---@field max_equipped_items? number
---@field screen_id? string id of the screen this entity is in
---@field render_character? string id of character sprite renderable
---@field stats? Stats
---@field attack_timer? number
---@field money? number
---@field escort_clients? string[] ids of characters being escorted
---@field x? number
---@field y? number
---@field vy? number
---@field gravity? number
---@field floor_y? number
---@field jump_velocity? number
---@field floor_behavior? 'stand'|'bounce'|'fall'
---@field max_jumps? number
---@field jumps? number
---@field class? Class
---@field subclass? string

---@alias Class 'warrior'|'archer'|'mage'|'rogue' base classs

---@class Health
---@field current number
---@field max number

---@alias Room 'combat'|'shop'|'rest'|'event'