---@class Entity
---@field _id? string
---@field tag? string appended to _id
---@field name? string
---@field group? 'player'|'enemy'|'ally'
---@field inventory? ItemData[]
---@field max_inventory_items? number
---@field equipped_items? ItemData[]
---@field max_equipped_items? number
---@field class? Class
---@field screen_id? string id of the screen this entity is in
---@field health? Health
---@field stats? Stats
---@field defense? number
---@field critical? Critical
---@field attack_timer? number
---@field money? number
---@field escort_clients? string[] ids of characters being escorted
---@field x? number
---@field y? number
---@field vx? number
---@field vy? number
---@field gravity? number
---@field floor_y? number
---@field jump_velocity? number
---@field floor_behavior? 'stand'|'bounce'|'fall'
---@field max_jumps? number
---@field jumps? number
---@field subclass? string
---@field render_text? string
---@field render_text_animation? string Animation
---@field character_sprite? CharacterSprite
---@field is_in_combat? boolean

---@alias Class 'adventurer'|'warrior'|'archer'|'mage'|'rogue' base classs

---@class Health
---@field current number
---@field max number

---@class Critical
---@field chance number [0,1]
---@field damage number

---@alias Room 'combat'|'shop'|'rest'|'event'